name: "OpenCart Documentation"
description: "Documentation for the OpenCart script from www.opencart.com"
url: "http://www.opencart.com"
baseurl: "http://opencart.github.io/"
markdown: rdiscount
permalink: pretty